name: Bug Report
description: File a reproducible bug report.
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Include steps to reproduce and expected behavior.
      placeholder: |
        Steps:
        1.
        2.

        Expected:

        Actual:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs (redact secrets).
      render: shell

  - type: input
    id: version
    attributes:
      label: Version / commit
      placeholder: "e.g. main @ abc1234"

  - type: textarea
    id: agent_state
    attributes:
      label: Agent State / Work Log
      description: Keep this updated while work is in progress so another agent can resume. Do not include secrets or private infrastructure details.
      value: |
        Status:
        Branch:
        Last verified (lint/tests):
        How to reproduce:
        Next steps:
        Notes (no secrets, no private infra):
