name: Task
description: A small unit of work with clear acceptance criteria.
labels: ["task"]
body:
  - type: textarea
    id: what
    attributes:
      label: What
      description: One sentence describing what this issue implements.
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why
      description: How this connects to the project goals.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List specific, testable conditions.
      value: |
        - [ ] ...
        - [ ] Unit tests cover the implemented code
        - [ ] CI green
        - [ ] Smoke test required: YES / NO

  - type: input
    id: deps
    attributes:
      label: Dependencies
      description: "Depends on issue(s) (if any)."
      placeholder: "#123"

  - type: textarea
    id: agent_state
    attributes:
      label: Agent State / Work Log
      description: Keep this updated while work is in progress so another agent can resume. Do not include secrets or private infrastructure details.
      value: |
        Status:
        Branch:
        Last verified (lint/tests):
        How to reproduce:
        Next steps:
        Notes (no secrets, no private infra):
